### ISSUE TITLE
Front or back end?

### ISSUE THREAD

**Issue by jycr753** [DK-Hostmaster/DAS#1]
Front or back end? will this fix the issue with the domain admin? finally dk-hostmaster is changing interface? :)

**Comment by jonasbn** [comment]
This is just a new home for the DAS specification, it is currently available in a proprietary format on the [DK Hostmaster website](https://www.dk-hostmaster.dk/english/technical-administration/tech-notes/das/), migrating it to markdown and hosting it on Github, makes it easier to maintain and collaborate.

So you comment/question is not really appropriate for this forum.
